openapi: 3.0.1
info:
  title: Danger Zones MicroService
  description: REST microservice to create, get and delete danger zones. A danger zone is a circular area where the device should stay for a period of time. If the devices goes outside the zone before the time or stay inside after time, an alarm will be triggered and the zone will be deleted.
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: dangerzone
    description: Danger zones endpoints
paths:
  /dangerzones:
    post:
      tags:
        - dangerzone
      summary: Create a danger zone
      description: Create a new danger zone for the device ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DangerzoneCreate'
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dangerzone'
        '400':
          description: Invalid input
    get:
      tags:
        - dangerzone
      summary: Get danger zones
      description: Get all danger zones active for a given company ID.
      parameters:
        - name: device_id
          in: query
          description: Filter by device_id. If this param is given it will return only the danger zone for the device ID.
          required: false
          schema:
            type: string
        - name: company_id
          in: query
          description: Filter by company_id. If this param is given it will return only the danger zones for the company ID.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Array of danger zones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dangerzone'
        '400':
          description: Invalid input
        '404':
          description: No danger zone for device_id
    delete:
      tags:
        - dangerzone
      summary: Delete danger zone by device ID
      parameters:
        - name: device_id
          in: query
          description: Device ID related to the danger zone
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Deleted successfully
        '400':
          description: Invalid input
components:
  schemas:
    Dangerzone:
      type: object
      properties:
        device_id:
          type: string
          example: ABCDEFG
        longitude:
          type: number
          format: float
          example: 123.456
        latitude:
          type: number
          format: float
          example: -123.456
        radius:
          type: number
          format: float
          example: 2.45
        end_timestamp:
          type: integer
          format: int64
          example: 1234567890
          description: Time when the zone expires
    DangerzoneCreate:
      type: object
      properties:
        device_id:
          type: string
          example: ABCDEFG
        longitude:
          type: number
          format: float
          example: 123.456
        latitude:
          type: number
          format: float
          example: -123.456
        radius:
          type: number
          format: float
          example: 2.45
        ttl:
          type: integer
          format: int64
          example: 3600
          description: Time to live of the zone in seconds
        country_id:
          type: integer
          format: int64
          example: 1
          description: Country ID needed for alarm.